# Limite à 2Go pour éviter le crash de la JVM sur Windows
org.gradle.jvmargs=-Xmx2048m -XX:MaxMetaspaceSize=512m -Dfile.encoding=UTF-8

# Crucial : Désactiver le daemon pour éviter le message "Daemon disappeared"
org.gradle.daemon=false

# Désactive le parallélisme pour économiser le CPU pendant la compilation Kotlin
org.gradle.parallel=false
org.gradle.configureondemand=false

# Compatibilité AndroidX (Indispensable pour Firebase/GetX)
android.useAndroidX=true
android.enableJetifier=true

# Désactive le cache incrémental qui cause souvent les "Incompatible Metadata"
kotlin.incremental=false