// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAymJCA0pd38MOzy2Y683JBscLlwJBEqUM',
    appId: '1:911711078083:web:46db3898abec0675ee4476',
    messagingSenderId: '911711078083',
    projectId: 'smart-irrigation-pfe-a52f7',
    authDomain: 'smart-irrigation-pfe-a52f7.firebaseapp.com',
    storageBucket: 'smart-irrigation-pfe-a52f7.firebasestorage.app',
    measurementId: 'G-DCG1PGC1VD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOn_9mktsrniE1vcEJXwGP9sg8hAnObc8',
    appId: '1:911711078083:android:78cee1e1df6dda07ee4476',
    messagingSenderId: '911711078083',
    projectId: 'smart-irrigation-pfe-a52f7',
    storageBucket: 'smart-irrigation-pfe-a52f7.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyD9ZNOwPO65idMXA-Dgt_TRjNEqk0mSMyw',
    appId: '1:911711078083:ios:dc93d23b0acb85bcee4476',
    messagingSenderId: '911711078083',
    projectId: 'smart-irrigation-pfe-a52f7',
    storageBucket: 'smart-irrigation-pfe-a52f7.firebasestorage.app',
    iosClientId: '911711078083-o15bl71b5fd9m12jcbnfdclf581m9akb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarm',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyD9ZNOwPO65idMXA-Dgt_TRjNEqk0mSMyw',
    appId: '1:911711078083:ios:dc93d23b0acb85bcee4476',
    messagingSenderId: '911711078083',
    projectId: 'smart-irrigation-pfe-a52f7',
    storageBucket: 'smart-irrigation-pfe-a52f7.firebasestorage.app',
    iosClientId: '911711078083-o15bl71b5fd9m12jcbnfdclf581m9akb.apps.googleusercontent.com',
    iosBundleId: 'com.example.smartFarm',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAymJCA0pd38MOzy2Y683JBscLlwJBEqUM',
    appId: '1:911711078083:web:21d77dfe7741b91cee4476',
    messagingSenderId: '911711078083',
    projectId: 'smart-irrigation-pfe-a52f7',
    authDomain: 'smart-irrigation-pfe-a52f7.firebaseapp.com',
    storageBucket: 'smart-irrigation-pfe-a52f7.firebasestorage.app',
    measurementId: 'G-Q6SMMN1FS7',
  );

}